{%- if cookiecutter.docker == 'y' %}
version: "3"
services:
  core:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PUID: !!PUID!!
        PGID: !!PGID!!
        WORKDIR: /package
        VERSION: {{ cookiecutter.version }}
    image: {{ cookiecutter.package_name }}-core:{{ cookiecutter.version }}
    container_name: {{ cookiecutter.package_name }}-core
    user: lincoln
    volumes:
      - "${PWD}:/package"
    env_file:
      - .env
    networks:
      - default
{% endif %}