# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python35:
      python.version: '3.5'
      TOXENV: 'py35'
    Python36:
      python.version: '3.6'
      TOXENV: 'py36'
    Python37:
      python.version: '3.7'
      TOXENV: 'py37, docs, flake8'

steps:
- task: UsePythonVersion@0
  displayName: Use version '$(python.version)'
  inputs:
    versionSpec: '$(python.version)'

- script: |
    pip install -U pip
    pip install tox
  displayName: 'Install Tox'

- script: tox
  displayName: 'Run Tox'
